name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v3
     
     - name: Push dockerhub
       uses: mr-smithers-excellent/docker-build-push@v5
       with:
        image: 3dspace/microstitching
        tags: latest
        registry: docker.io
        username: ${{secrets.DOCKER_MAIL}}
        password: ${{secrets.DOCKER_PASSWD}}
