name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
     - name: Push dockerhub
     - uses: mr-smithers-excellent/docker-build-push@v5
     - with:
        image: seaman69/3dspace
        tags: stitching
        registry: docker.io
        username: ${{secrets.DOCKER_MAIL}}
        password: ${{secrets.DOCKER_PASSWD}}
